# Generated by Django 4.2.10 on 2024-03-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactrequest_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRequest',
            new_name='Contact',
        ),
    ]
