# Generated by Django 4.2.10 on 2024-03-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contact_attachments')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='attachment',
        ),
        migrations.AddField(
            model_name='contact',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='contact.attachment'),
        ),
    ]
