# Generated by Django 4.2.10 on 2024-03-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_attachment_remove_contact_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
