# Generated by Django 4.2.10 on 2024-03-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_attachments_contact_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='attachment',
        ),
        migrations.AddField(
            model_name='contact',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
