# Generated by Django 4.2.10 on 2024-03-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_contact_attachment_contact_attachments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='attachments',
            new_name='attachment',
        ),
    ]
