# Generated by Django 4.2.4 on 2024-02-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appuser_is_sharer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'permissions': [('is_sharer', 'Can be a sharer')]},
        ),
    ]
