# Generated by Django 5.0.1 on 2024-02-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_besharer'),
        ('sharer', '0004_remove_sharer_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follower', to='sharer.sharer'),
        ),
    ]
