# Generated by Django 4.2.4 on 2024-02-23 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_besharer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='besharer',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
