# Generated by Django 4.2.10 on 2024-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_besharer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/default/default.png', null=True, upload_to='uploads/images'),
        ),
    ]
