# Generated by Django 4.2.10 on 2024-03-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rating_sharer_alter_rating_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
