# Generated by Django 4.2.10 on 2024-03-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_delete_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
