# Generated by Django 4.2.10 on 2024-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0096_delete_tier'),
        ('accounts', '0029_alter_appuser_is_superuser_alter_appuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='follows',
        ),
        migrations.AddField(
            model_name='appuser',
            name='follows_tier1',
            field=models.ManyToManyField(blank=True, related_name='follower_tier1', to='sharer.sharer'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='follows_tier2',
            field=models.ManyToManyField(blank=True, related_name='follower_tier2', to='sharer.sharer'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='follows_tier3',
            field=models.ManyToManyField(blank=True, related_name='follower_tier3', to='sharer.sharer'),
        ),
    ]
