# Generated by Django 5.0.3 on 2024-03-30 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_appuser_follows_appuser_follows_tier1_and_more'),
        ('sharer', '0112_remove_dashboard_twenty_percent_less_earning_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowTier1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharer.sharer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowTier2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharer.sharer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowTier3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharer.sharer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
