# Generated by Django 5.0.3 on 2024-03-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_followtier1_followtier2_followtier3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followtier2',
            name='sharer',
        ),
        migrations.RemoveField(
            model_name='followtier2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='followtier3',
            name='sharer',
        ),
        migrations.RemoveField(
            model_name='followtier3',
            name='user',
        ),
        migrations.DeleteModel(
            name='FollowTier1',
        ),
        migrations.DeleteModel(
            name='FollowTier2',
        ),
        migrations.DeleteModel(
            name='FollowTier3',
        ),
    ]
