# Generated by Django 5.0.3 on 2024-03-30 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_followtier2_sharer_remove_followtier2_user_and_more'),
        ('sharer', '0112_remove_dashboard_twenty_percent_less_earning_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowExpiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharer.sharer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
