# Generated by Django 4.2.4 on 2024-02-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0004_remove_sharer_follows'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('description', models.CharField(max_length=10000000000)),
            ],
        ),
    ]
