# Generated by Django 4.2.4 on 2024-02-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0005_sharerupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerupload',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/documents'),
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos'),
        ),
    ]
