# Generated by Django 4.2.4 on 2024-02-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0006_sharerupload_document_sharerupload_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerupload',
            name='description',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='sharerupload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
