# Generated by Django 4.2.4 on 2024-02-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0008_remove_sharerupload_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerupload',
            name='image',
        ),
    ]
