# Generated by Django 4.2.4 on 2024-02-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0011_sharerupload_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerupload',
            name='creator',
        ),
    ]
