# Generated by Django 4.2.4 on 2024-02-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0014_sharer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
