# Generated by Django 4.2.4 on 2024-02-23 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0016_alter_sharer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
