# Generated by Django 4.2.4 on 2024-02-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0018_sharer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharer',
            name='created_at',
        ),
    ]
