# Generated by Django 4.2.4 on 2024-02-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0022_sharer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerupload',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='sharer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upload', to='sharer.sharer'),
            preserve_default=False,
        ),
    ]
