# Generated by Django 4.2.4 on 2024-02-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0024_remove_sharerupload_sharer_sharerupload_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='created_at',
        ),
    ]
