# Generated by Django 4.2.4 on 2024-02-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0025_remove_sharer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerupload',
            name='uploaded_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='sharer.sharer'),
        ),
    ]
