# Generated by Django 4.2.4 on 2024-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0033_remove_sharerupload_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
