# Generated by Django 4.2.10 on 2024-02-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0035_like_unliked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
