# Generated by Django 4.2.10 on 2024-02-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0036_rename_content_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
    ]
