# Generated by Django 4.2.10 on 2024-03-02 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharer', '0038_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
