# Generated by Django 4.2.10 on 2024-03-11 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0041_sharer_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharer',
            old_name='name',
            new_name='page_name',
        ),
    ]
