# Generated by Django 4.2.10 on 2024-03-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0042_rename_name_sharer_page_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharer',
            old_name='page_name',
            new_name='name',
        ),
    ]
