# Generated by Django 4.2.10 on 2024-03-11 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0043_rename_page_name_sharer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharer',
            name='username',
        ),
    ]
