# Generated by Django 4.2.10 on 2024-03-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0044_remove_sharer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
