# Generated by Django 4.2.10 on 2024-03-11 05:30

from django.db import migrations, models
import sharer.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0045_sharer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='image',
            field=models.ImageField(upload_to=sharer.models.upload_image),
        ),
        migrations.AlterField(
            model_name='sharerupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sharer.models.upload_image),
        ),
    ]
