# Generated by Django 4.2.10 on 2024-03-11 11:17

from django.db import migrations, models
import sharer.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0046_alter_sharer_image_alter_sharerupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharerupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=sharer.models.upload_file),
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=sharer.models.upload_video),
        ),
    ]
