# Generated by Django 4.2.10 on 2024-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0048_alter_sharerupload_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos'),
        ),
    ]
