# Generated by Django 4.2.10 on 2024-03-12 11:42

from django.db import migrations, models
import sharer.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0050_alter_sharerupload_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sharer.models.upload_file)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sharer.models.upload_image)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=sharer.models.upload_video)),
            ],
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='video',
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='files',
            field=models.ManyToManyField(blank=True, to='sharer.file'),
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='images',
            field=models.ManyToManyField(blank=True, to='sharer.image'),
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='videos',
            field=models.ManyToManyField(blank=True, to='sharer.video'),
        ),
    ]
