# Generated by Django 4.2.10 on 2024-03-12 12:33

from django.db import migrations, models
import django.db.models.deletion
import sharer.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0053_remove_sharerupload_file_remove_sharerupload_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='video',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=sharer.models.upload_video)),
                ('sharer_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sharer.sharerupload')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sharer.models.upload_image)),
                ('sharer_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sharer.sharerupload')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=sharer.models.upload_file)),
                ('sharer_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sharer.sharerupload')),
            ],
        ),
    ]
