# Generated by Django 4.2.10 on 2024-03-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0055_remove_image_sharer_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='video',
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='file',
            field=models.ManyToManyField(blank=True, to='sharer.file'),
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='image',
            field=models.ManyToManyField(blank=True, to='sharer.image'),
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='video',
            field=models.ManyToManyField(blank=True, to='sharer.video'),
        ),
    ]
