# Generated by Django 4.2.10 on 2024-03-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0056_file_image_video_remove_sharerupload_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharerupload',
            old_name='file',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='sharerupload',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='sharerupload',
            old_name='video',
            new_name='videos',
        ),
    ]
