# Generated by Django 4.2.10 on 2024-03-12 12:53

from django.db import migrations, models
import sharer.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0057_rename_file_sharerupload_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerupload',
            name='files',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='images',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='videos',
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=sharer.models.upload_file),
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sharer.models.upload_image),
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=sharer.models.upload_video),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
