# Generated by Django 4.2.10 on 2024-03-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0059_file_image_video_remove_sharerupload_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharerupload',
            old_name='files',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='sharerupload',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sharerupload',
            old_name='videos',
            new_name='video',
        ),
    ]
