# Generated by Django 4.2.10 on 2024-03-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0068_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.RemoveField(
            model_name='sharer',
            name='username',
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='category',
            field=models.CharField(choices=[('', 'Not specified'), ('Art', 'Art'), ('Comics', 'Comics')], max_length=30),
        ),
    ]
