# Generated by Django 4.2.10 on 2024-03-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0069_remove_comment_username_remove_sharer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerupload',
            name='edited_at',
        ),
    ]
