# Generated by Django 4.2.10 on 2024-03-17 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0070_remove_sharerupload_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharerupload',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='category',
            field=models.CharField(choices=[('', 'Not specified'), ('Art', 'Art'), ('Comics', 'Comics'), ('Writing', 'Writing'), ('Music', 'Music'), ('Podcasts', 'Podcasts'), ('Video & Film', 'Video & Film'), ('Photography', 'Photography'), ('Crafts & DIY', 'Crafts & DIY'), ('Dance & Theater', 'Dance & Theater'), ('Gaming', 'Gaming'), ('Education', 'Education'), ('Science', 'Science'), ('Technology', 'Technology'), ('Health & Fitness', 'Health & Fitness'), ('Lifestyle', 'Lifestyle'), ('Fashion & Beauty', 'Fashion & Beauty'), ('Food & Cooking', 'Food & Cooking'), ('Travel & Outdoor', 'Travel & Outdoor'), ('Business & Entrepreneurship', 'Business & Entrepreneurship'), ('Parenting & Family', 'Parenting & Family')], max_length=30),
        ),
    ]
