# Generated by Django 4.2.10 on 2024-03-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0071_sharer_username_sharerupload_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
