# Generated by Django 4.2.10 on 2024-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0072_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_picture',
            field=models.ImageField(blank=True, default='uploads/default/default.png', null=True, upload_to='uploads/images'),
        ),
    ]
