# Generated by Django 4.2.10 on 2024-03-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0073_comment_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
