# Generated by Django 4.2.10 on 2024-03-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0075_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
    ]
