# Generated by Django 4.2.10 on 2024-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0076_remove_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharer',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
    ]
