# Generated by Django 4.2.10 on 2024-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0078_alter_sharer_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='has_rated',
            field=models.BooleanField(default=False),
        ),
    ]
