# Generated by Django 4.2.10 on 2024-03-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0081_sharerupload_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharerupload',
            name='visibility',
            field=models.CharField(choices=[('ALL', 'All (followers and non-followers)'), ('FOLLOWERS', 'Followers only')], default='ALL', max_length=20),
        ),
    ]
