# Generated by Django 4.2.10 on 2024-03-20 14:28

from django.db import migrations, models
import django.db.models.deletion
import sharer.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0082_alter_sharerupload_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharerupload',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sharerupload',
            name='video',
        ),
        migrations.CreateModel(
            name='SharerUploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=sharer.models.upload_video)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sharer.sharerupload')),
            ],
        ),
        migrations.CreateModel(
            name='SharerUploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sharer.models.upload_image)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sharer.sharerupload')),
            ],
        ),
        migrations.CreateModel(
            name='SharerUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=sharer.models.upload_file)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sharer.sharerupload')),
            ],
        ),
    ]
