# Generated by Django 4.2.10 on 2024-03-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0085_alter_dashboard_total_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
