# Generated by Django 4.2.10 on 2024-03-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0087_dashboard_average_rating_dashboard_total_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='total_comments',
        ),
    ]
