# Generated by Django 4.2.10 on 2024-03-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0088_remove_dashboard_total_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='total_posts',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='total_unlikes',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='total_uploads',
        ),
    ]
