# Generated by Django 4.2.10 on 2024-03-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0089_remove_dashboard_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_unlikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='total_uploads',
            field=models.IntegerField(default=0),
        ),
    ]
