# Generated by Django 4.2.10 on 2024-03-24 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0092_alter_tipbox_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipbox',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
