# Generated by Django 4.2.10 on 2024-03-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0095_tier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
