# Generated by Django 4.2.10 on 2024-03-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0101_sharer_followers_tier1_sharer_followers_tier2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharer',
            name='followers_tier1',
        ),
        migrations.RemoveField(
            model_name='sharer',
            name='followers_tier2',
        ),
        migrations.RemoveField(
            model_name='sharer',
            name='followers_tier3',
        ),
    ]
