# Generated by Django 5.0.3 on 2024-03-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0104_alter_sharerupload_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='sharer_identifier',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
