# Generated by Django 5.0.3 on 2024-03-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0106_remove_dashboard_sharer_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
