# Generated by Django 5.0.3 on 2024-03-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0107_dashboard_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='email',
        ),
    ]
