# Generated by Django 5.0.3 on 2024-03-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0108_remove_dashboard_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='twenty_percent_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='twenty_percent_less_earning_send',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
