# Generated by Django 5.0.3 on 2024-03-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0114_alter_sharer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
