# Generated by Django 5.0.3 on 2024-04-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0115_alter_sharer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='twenty_percent_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='twenty_percent_less_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
