# Generated by Django 5.0.3 on 2024-04-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0120_alter_sharer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
