# Generated by Django 5.0.3 on 2024-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0121_alter_sharer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
