# Generated by Django 5.0.3 on 2024-04-15 09:49

import sharer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharer', '0132_alter_shareruploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareruploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=sharer.models.upload_file),
        ),
    ]
